lc_messages = 'Russian_Russia.1251'         
lc_monetary = 'Russian_Russia.1251'         
lc_numeric = 'Russian_Russia.1251'          
lc_time = 'Russian_Russia.1251'             
default_text_search_config = 'pg_catalog.russian'